name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |
              gE6T_M8gIOGcVBBc2AWeBA/field/password > env:PASSWORD
              gE6T_M8gIOGcVBBc2AWeBA/field/login > env:IP
              
      - name: Deploy to EC2
        run: |
          sshpass -p ${{ env.PASSWORD }} ssh -T -o StrictHostKeyChecking=no deployuser@${{ env.IP }} <<EOF
          cd /home/ubuntu/my-node-app && git pull && sudo npm install && sudo pm2 restart app.js
          EOF

