name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true  # Enable debug logging
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |
              PokOlMGzksRw60fYs6M5oA/field/password > EC2_PASSWORD
              PokOlMGzksRw60fYs6M5oA/field/login > env:EC2_IP
      - name: Print password
        run: |
          echo "EC2 IP is ${{ env.EC2_IP }}"
          
      - name: Deploy to EC2
        run: |
          sshpass -p ${{ env.EC2_PASSWORD }} ssh -T -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} <<EOF
          cd /home/ubuntu/my-node-app && git pull && npm install && pm2 restart app.js
          EOF
