name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests (optional)
      run: npm test  # You can skip this step if you don't have tests

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to EC2
      run: |
        sshpass -p 20241110 ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} <<EOF
          cd /path/to/your-app && git pull && npm install && pm2 restart app
        EOF
      env:
        EC2_PUBLIC_IP: 54.199.72.206
